# This file provides instructions for packaging.

`returning`
	deps:runtime-requirement     [ deps:on "Scalar::Util 1.11"^^deps:CpanId ];
	deps:runtime-requirement     [ deps:on "Scope::Upper 0.16"^^deps:CpanId ];
	deps:runtime-requirement     [ deps:on "Sub::Install 0.900"^^deps:CpanId ];
	deps:runtime-requirement     [ deps:on "Sub::Name 0.03"^^deps:CpanId ];
	deps:test-requirement        [ deps:on "Test::More 0.96"^^deps:CpanId ];
	deps:develop-recommendation  [ deps:on "Dist::Inkt 0.012"^^deps:CpanId ].
