# This file provides instructions for packaging.

`returning`
	perl_version_from m`returning`;
	version_from      m`returning`;
	readme_from       m`returning`;
	requires          p`Scalar::Util 1.11`;
	requires          p`Scope::Upper 0.16`;
	requires          p`Sub::Install 0.900`;
	requires          p`Sub::Name 0.03`;
	test_requires     p`Test::More 0.61`.

